// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    buildscript {
        ext.kotlin_version = '1.9.24'
        ext.butterknife_version = '8.8.1'
        ext.compile_sdk_version = 35
    }

    repositories {
        maven { url 'https://maven.google.com/' }
        mavenCentral()
        google()
        maven { url "https://plugins.gradle.org/m2/"}
        maven { url 'https://jitpack.io' }
        maven { url 'https://repo1.maven.org/maven2/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }

}

allprojects {
    repositories {
        google()
        maven { url 'https://maven.google.com/' }
        mavenCentral()

        maven { url "https://plugins.gradle.org/m2/"}
        maven { url 'https://jitpack.io' }
        maven { url 'https://repo1.maven.org/maven2/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
