name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create gradle property file
      env:
        token: ${{ secrets.GITHUBTOKEN }}
        name: ${{ secrets.GITHUBUSERNAME }}
      run: |
        touch local.properties
        echo githubToken="$token" >> local.properties
        echo githubUserName="$name" >> local.properties
        echo "end of properties"
      shell: bash
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        githubToken: ${{ secrets.GITHUBTOKEN }}
        githubUserName: ${{ secrets.GITHUBUSERNAME }}
      run: ./gradlew build
